"""Generate a torrc for a dedicated tor instance on Windows.

Key differences from the Linux torrc:
* No ``TransPort`` - tor does not support transparent proxying on Windows.
  Enforcement is done with the SOCKS proxy + firewall kill-switch instead.
* No ``User`` directive - the process runs as the (elevated) launching user.
* Windows-style paths for DataDirectory, and GeoIP files are pointed at the
  files shipped with the Tor bundle (extracted from the bundled Tor.zip) when found.
"""
from __future__ import annotations

import os
import shutil

from . import DATA_DIR, LOG_DIR
from .config import Config


def _plugin_path(tor_dir: str | None, *names: str) -> str | None:
    for n in names:
        p = shutil.which(n)
        if p:
            return p
    if tor_dir:
        # Search the tor directory itself, and also the PluggableTransports
        # subdirectory (used by the Tor Expert Bundle / bundled Tor.zip).
        search_dirs = [
            tor_dir,
            os.path.join(tor_dir, "PluggableTransports"),
            os.path.join(os.path.dirname(tor_dir), "PluggableTransports"),
        ]
        for d in search_dirs:
            for n in names:
                cand = os.path.join(d, n if n.endswith(".exe") else n + ".exe")
                if os.path.exists(cand):
                    return cand
    return None


def _transport_line(cfg: Config, tor_dir: str | None) -> str | None:
    bt = cfg.bridge_type
    if bt in ("obfs4", "meek_lite", "custom"):
        path = _plugin_path(tor_dir, "obfs4proxy", "lyrebird")
        if path:
            path = path.replace("\\", "\\\\")
            return f'ClientTransportPlugin obfs4,meek_lite exec "{path}"'
    elif bt == "snowflake":
        path = _plugin_path(tor_dir, "snowflake-client", "snowflake")
        if path:
            path = path.replace("\\", "\\\\")
            return f'ClientTransportPlugin snowflake exec "{path}"'
    elif bt == "webtunnel":
        path = _plugin_path(tor_dir, "webtunnel-client", "webtunnel")
        if path:
            path = path.replace("\\", "\\\\")
            return f'ClientTransportPlugin webtunnel exec "{path}"'
    return None


def _bridge_lines(cfg: Config, tor_dir: str | None) -> list[str]:
    if not cfg.use_bridges:
        return []
    lines = ["UseBridges 1"]
    plug = _transport_line(cfg, tor_dir)
    if plug:
        lines.append(plug)
    for br in cfg.custom_bridges:
        br = br.strip()
        if br and not br.startswith("#"):
            if not br.lower().startswith("bridge "):
                br = "Bridge " + br
            lines.append(br)
    return lines


def _geoip_lines(tor_dir: str | None) -> list[str]:
    if not tor_dir:
        return []
    out = []
    geoip = os.path.join(tor_dir, "geoip")
    geoip6 = os.path.join(tor_dir, "geoip6")
    # Tor Browser ships these under ...\Tor\ or a sibling \Data\Tor\.
    for base in (tor_dir, os.path.join(os.path.dirname(tor_dir), "Data", "Tor")):
        g = os.path.join(base, "geoip")
        g6 = os.path.join(base, "geoip6")
        if os.path.exists(g):
            geoip, geoip6 = g, g6
            break
    if os.path.exists(geoip):
        geoip_clean = geoip.replace("\\", "\\\\")
        out.append(f'GeoIPFile "{geoip_clean}"')
    if os.path.exists(geoip6):
        geoip6_clean = geoip6.replace("\\", "\\\\")
        out.append(f'GeoIPv6File "{geoip6_clean}"')
    return out


def build(cfg: Config, tor_dir: str | None = None) -> str:
    tor_data = os.path.join(DATA_DIR, "tor").replace("\\", "\\\\")
    tor_log = os.path.join(LOG_DIR, "tor.log")
    lines = [
        "# Generated by torchain (Windows) - do not edit by hand.",
        "Log notice file %s" % tor_log,
        "ClientOnly 1",
        "SocksPort 127.0.0.1:%d" % cfg.socks_port,
        "DNSPort 127.0.0.1:%d" % cfg.dns_port,
        "AutomapHostsOnResolve 1",
        "AutomapHostsSuffixes .onion,.exit",
        "VirtualAddrNetworkIPv4 10.192.0.0/10",
        "ControlPort 127.0.0.1:%d" % cfg.control_port,
        "CookieAuthentication 1",
        'DataDirectory "%s"' % tor_data,
        "AvoidDiskWrites 1",
        "LearnCircuitBuildTimeout 0",
        "CircuitBuildTimeout 10",
        "KeepalivePeriod 60",
        "NewCircuitPeriod 120",
        "NumEntryGuards 3",
    ]
    lines.extend(_geoip_lines(tor_dir))
    if cfg.block_ipv6:
        lines.append("ClientUseIPv6 0")
    else:
        lines.append("ClientUseIPv6 1")
    if cfg.exit_country:
        cc = cfg.exit_country.lower()
        lines.append("ExitNodes {%s}" % cc)
        lines.append("StrictNodes 1")
    lines.extend(_bridge_lines(cfg, tor_dir))
    return "\n".join(lines) + "\n"


def write(cfg: Config, path: str, tor_dir: str | None = None) -> None:
    content = build(cfg, tor_dir)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(content)
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, path)
