"""Generate a minimal, fast-bootstrapping torrc for a dedicated tor instance.

Design choices for speed + low memory:
- A dedicated DataDirectory so guard state persists -> fast reconnects.
- AvoidDiskWrites 1 to cut I/O churn.
- ClientOnly 1, no relaying.
- TransPort/DNSPort/ControlPort bound to loopback only.
- Cookie auth for a secure, password-less control channel.
- No obsolete options (clean against modern tor).
"""
from __future__ import annotations

import os
import re
import shutil

from . import DATA_DIR
from .config import Config


def _plugin_path(*names: str) -> str | None:
    for n in names:
        p = shutil.which(n)
        if p:
            return p
    return None


def _transport_for_line(line: str) -> str | None:
    m = re.match(r"^(?:bridge\s+)?(obfs4|snowflake|meek_lite|webtunnel)\b", line.strip(), re.I)
    return m.group(1).lower() if m else None


def _transport_lines(cfg: Config) -> list[str]:
    """Build ClientTransportPlugin lines for every transport we actually need.

    Instead of registering only the transport named in ``bridge_type``, we scan
    the actual bridge lines and emit a plugin for every distinct transport
    found. This fixes the case where a user pastes a webtunnel bridge line
    while ``bridge_type`` is still the default ``obfs4`` -- tor would reject
    the config because no ``ClientTransportPlugin webtunnel exec`` was present.
    """
    needed: list[str] = []

    # Collect transports referenced by the actual bridge lines.
    for br in cfg.custom_bridges:
        t = _transport_for_line(br)
        if t and t not in needed:
            needed.append(t)

    # Always include the configured type so plain bridges (without a PT prefix)
    # also get a plugin assigned.
    bt = cfg.bridge_type
    if bt not in needed and bt != "custom":
        needed.insert(0, bt)

    out: list[str] = []
    seen_lines: set[str] = set()
    for t in needed:
        if t in ("obfs4", "meek_lite"):
            path = _plugin_path("obfs4proxy", "lyrebird") or "/usr/bin/obfs4proxy"
            line = f"ClientTransportPlugin obfs4,meek_lite exec {path}"
        elif t == "snowflake":
            path = _plugin_path("snowflake-client", "snowflake") or "/usr/bin/snowflake-client"
            line = f"ClientTransportPlugin snowflake exec {path}"
        elif t == "webtunnel":
            path = _plugin_path("webtunnel-client", "webtunnel") or "/usr/bin/webtunnel-client"
            line = f"ClientTransportPlugin webtunnel exec {path}"
        else:
            continue
        if line not in seen_lines:
            seen_lines.add(line)
            out.append(line)
    return out


def _bridge_lines(cfg: Config) -> list[str]:
    if not cfg.use_bridges:
        return []
    lines = ["UseBridges 1"]
    lines.extend(_transport_lines(cfg))
    for br in cfg.custom_bridges:
        br = br.strip()
        if br and not br.startswith("#"):
            if not br.lower().startswith("bridge "):
                br = "Bridge " + br
            lines.append(br)
    return lines


def build(cfg: Config, tor_user: str | None = None) -> str:
    tor_data = os.path.join(DATA_DIR, "tor")
    lines = [
        "# Generated by torchain v5 - do not edit by hand.",
        "ClientOnly 1",
        "SocksPort 127.0.0.1:%d" % cfg.socks_port,
        "TransPort 127.0.0.1:%d IsolateClientAddr IsolateClientProtocol" % cfg.trans_port,
        "DNSPort 127.0.0.1:%d" % cfg.dns_port,
        "AutomapHostsOnResolve 1",
        "AutomapHostsSuffixes .onion,.exit",
        "VirtualAddrNetworkIPv4 10.192.0.0/10",
        "ControlPort 127.0.0.1:%d" % cfg.control_port,
        "CookieAuthentication 1",
        f"DataDirectory {tor_data}",
        "AvoidDiskWrites 1",
        # Fast, predictable bootstrap.
        "LearnCircuitBuildTimeout 0",
        "CircuitBuildTimeout 10",
        "KeepalivePeriod 60",
        "NewCircuitPeriod 120",
        "NumEntryGuards 3",
    ]
    if tor_user:
        lines.append(f"User {tor_user}")
    if cfg.block_ipv6:
        lines.append("ClientUseIPv6 0")
    else:
        lines.append("ClientUseIPv6 1")
    if cfg.exit_country:
        cc = cfg.exit_country.lower()
        lines.append("ExitNodes {%s}" % cc)
        lines.append("StrictNodes 1")
    lines.extend(_bridge_lines(cfg))
    return "\n".join(lines) + "\n"


def write(cfg: Config, path: str, tor_user: str | None = None) -> None:
    content = build(cfg, tor_user)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(content)
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, path)
