"""Generate a minimal, fast-bootstrapping torrc for a dedicated tor instance.

Design choices for speed + low memory:
- A dedicated DataDirectory so guard state persists -> fast reconnects.
- AvoidDiskWrites 1 to cut I/O churn.
- ClientOnly 1, no relaying.
- TransPort/DNSPort/ControlPort bound to loopback only.
- Cookie auth for a secure, password-less control channel.
- No obsolete options (clean against modern tor).
"""
from __future__ import annotations

import os
import shutil

from . import DATA_DIR
from .config import Config


def _plugin_path(*names: str) -> str | None:
    for n in names:
        p = shutil.which(n)
        if p:
            return p
    return None


def _transport_line(cfg: Config) -> str | None:
    """Build the ClientTransportPlugin line for the selected transport."""
    bt = cfg.bridge_type
    if bt in ("obfs4", "meek_lite", "custom"):
        path = _plugin_path("obfs4proxy", "lyrebird") or "/usr/bin/obfs4proxy"
        # 'custom' lines are usually obfs4, so register obfs4+meek_lite.
        return f"ClientTransportPlugin obfs4,meek_lite exec {path}"
    if bt == "snowflake":
        path = _plugin_path("snowflake-client", "snowflake") or "/usr/bin/snowflake-client"
        return f"ClientTransportPlugin snowflake exec {path}"
    if bt == "webtunnel":
        path = _plugin_path("webtunnel-client", "webtunnel") or "/usr/bin/webtunnel"
        return f"ClientTransportPlugin webtunnel exec {path}"
    return None


def _bridge_lines(cfg: Config) -> list[str]:
    if not cfg.use_bridges:
        return []
    lines = ["UseBridges 1"]
    plug = _transport_line(cfg)
    if plug:
        lines.append(plug)
    for br in cfg.custom_bridges:
        br = br.strip()
        if br and not br.startswith("#"):
            if not br.lower().startswith("bridge "):
                br = "Bridge " + br
            lines.append(br)
    return lines


def build(cfg: Config, tor_user: str | None = None) -> str:
    tor_data = os.path.join(DATA_DIR, "tor")
    lines = [
        "# Generated by torchain v5 - do not edit by hand.",
        "ClientOnly 1",
        "SocksPort 127.0.0.1:%d" % cfg.socks_port,
        "TransPort 127.0.0.1:%d IsolateClientAddr IsolateClientProtocol" % cfg.trans_port,
        "DNSPort 127.0.0.1:%d" % cfg.dns_port,
        "AutomapHostsOnResolve 1",
        "AutomapHostsSuffixes .onion,.exit",
        "VirtualAddrNetworkIPv4 10.192.0.0/10",
        "ControlPort 127.0.0.1:%d" % cfg.control_port,
        "CookieAuthentication 1",
        f"DataDirectory {tor_data}",
        "AvoidDiskWrites 1",
        # Fast, predictable bootstrap.
        "LearnCircuitBuildTimeout 0",
        "CircuitBuildTimeout 10",
        "KeepalivePeriod 60",
        "NewCircuitPeriod 120",
        "NumEntryGuards 3",
    ]
    if tor_user:
        lines.append(f"User {tor_user}")
    if cfg.block_ipv6:
        lines.append("ClientUseIPv6 0")
    else:
        lines.append("ClientUseIPv6 1")
    if cfg.exit_country:
        cc = cfg.exit_country.lower()
        lines.append("ExitNodes {%s}" % cc)
        lines.append("StrictNodes 1")
    lines.extend(_bridge_lines(cfg))
    return "\n".join(lines) + "\n"


def write(cfg: Config, path: str, tor_user: str | None = None) -> None:
    content = build(cfg, tor_user)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(content)
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, path)
